CREATE TABLE `joining_request_form_8371` (
		 `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
		 `date_modified` datetime DEFAULT NULL,
 		`admin_add_id` int(11) NOT NULL DEFAULT '0',
		 `date_created` datetime DEFAULT NULL,
	    `time_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		`deleted` tinyint(1) NOT NULL DEFAULT '0',
		`restricted` tinyint(1) NOT NULL DEFAULT '0',
        
		    `user` INT(11) DEFAULT NULL  COMMENT 'User',
		    `active` VARCHAR(250)  DEFAULT '0' COMMENT 'Active',
		    `submitted` VARCHAR(250)  DEFAULT '0' COMMENT 'Submitted',
		    `email_address` VARCHAR(250) DEFAULT NULL  COMMENT 'Email Address',
		    `confirm_email_address` VARCHAR(250) DEFAULT NULL  COMMENT 'Confirm Email Address',
		    `full_name` VARCHAR(250) DEFAULT NULL  COMMENT 'Full Name',
		    `full_name_en` VARCHAR(250) DEFAULT NULL  ,
		    `id_number` INT(11) DEFAULT NULL  COMMENT 'Id Number',
		    `gender` INT(11) DEFAULT NULL  COMMENT 'Gender',
		    `mobile_number` INT(11) DEFAULT NULL  COMMENT 'Mobile Number',
		    `palce_of_birth` VARCHAR(250) DEFAULT NULL  COMMENT 'Palce of Birth',
		    `date_of_birth` DATE DEFAULT NULL  COMMENT 'Date of Birth',
		    `social_situation` INT(11) DEFAULT NULL  COMMENT 'Social Situation',
		    `province_residence` INT(11) DEFAULT NULL  COMMENT 'Province of current residence',
		    `governorate_abroad` VARCHAR(250) DEFAULT NULL  COMMENT 'Governorate in case of residence abroad',
		    `mother_province` INT(11) DEFAULT NULL  COMMENT 'Mother province',
		    `home_adress` VARCHAR(250) DEFAULT NULL  COMMENT 'Home Adress',
		    `branch` INT(11) DEFAULT NULL  COMMENT 'Branch',
		    `average` INT(11) DEFAULT NULL  COMMENT 'Average',
		    `graduation_year` INT(11) DEFAULT NULL  COMMENT 'Graduation Year',
		    `country` INT(11) DEFAULT NULL  COMMENT 'Country',
		    `all_attested` VARCHAR(1000) DEFAULT NULL  COMMENT 'All University certificates (attested)',
		    `proof_passport` VARCHAR(1000) DEFAULT NULL  COMMENT 'Proof of identity (identity / passport)',
		    `high_attested` VARCHAR(1000) DEFAULT NULL  COMMENT 'High school certificate (attested)',
		    `certificate_conduct` VARCHAR(1000) DEFAULT NULL  COMMENT 'Certificate of non-conviction / good conduct',
		    `work_proof` VARCHAR(1000) DEFAULT NULL  COMMENT 'Work Proof',
		    `bank_receipt` VARCHAR(1000) DEFAULT NULL  COMMENT 'Bank Receipt',
		    `confirm_that` BOOLEAN DEFAULT NULL  COMMENT 'I declare that all the information including the academic certificates in the application are correct, and in the event that it turns out otherwise, the Association has the right to withdraw its decision to register me as a member, and I also bear the civil and criminal legal responsibility resulting from that.',
PRIMARY KEY (`id`),
INDEX (`deleted`)

) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;