CREATE TABLE `files_1577206823` (
		 `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
		 `date_modified` datetime DEFAULT NULL,
 		`admin_add_id` int(11) NOT NULL DEFAULT '0',
		 `date_created` datetime DEFAULT NULL,
	    `time_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		`deleted` tinyint(1) NOT NULL DEFAULT '0',
		`restricted` tinyint(1) NOT NULL DEFAULT '0',
        
		    `full_name` VARCHAR(250) DEFAULT NULL  COMMENT 'Full Name',
		    `name` VARCHAR(250) DEFAULT NULL  COMMENT 'Name',
		    `original_name` VARCHAR(250) DEFAULT NULL  COMMENT 'Original Name',
		    `protected_file` BOOLEAN  DEFAULT '0' COMMENT 'Protected File',
		    `related_module` INT(11) DEFAULT NULL  COMMENT 'Related Module',
		    `related_module_id` INT(11) DEFAULT NULL  COMMENT 'Related Module ID',
		    `uploader_module_prefix` INT(11) DEFAULT NULL  COMMENT 'Uploader Module Prefix',
		    `uploader_user_id` INT(11) DEFAULT NULL  COMMENT 'Uploader User ID',
		    `extension` VARCHAR(10) DEFAULT NULL  COMMENT 'Extension',
		    `height` INT(11) DEFAULT NULL  COMMENT 'Height',
		    `width` INT(11) DEFAULT NULL  COMMENT 'Width',
		    `quality` INT(11) DEFAULT NULL  COMMENT 'Quality',
		    `type` VARCHAR(250) DEFAULT NULL  COMMENT 'Type',
		    `sub_type` VARCHAR(250) DEFAULT NULL  COMMENT 'Sub Type',
		    `size` DOUBLE DEFAULT NULL  COMMENT 'Size',
		    `source_name` VARCHAR(250) DEFAULT NULL  COMMENT 'Source Name',
		    `source_link` VARCHAR(1000) DEFAULT NULL  COMMENT 'Source Link',
		    `reference` VARCHAR(250) DEFAULT NULL  COMMENT 'Reference',
		    `average_color` VARCHAR(10) DEFAULT NULL  COMMENT 'Average Color',
		    `credit` VARCHAR(250) DEFAULT NULL  COMMENT 'Credit',
		    `credit_link` VARCHAR(1000) DEFAULT NULL  COMMENT 'Credit Link',
		    `caption` TEXT DEFAULT NULL  COMMENT 'Caption',
PRIMARY KEY (`id`),
INDEX (`deleted`)
,INDEX (`full_name`),INDEX (`name`),INDEX (`protected_file`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;