CREATE TABLE `statistics_8324` (
		 `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
		 `date_modified` datetime DEFAULT NULL,
 		`admin_add_id` int(11) NOT NULL DEFAULT '0',
		 `date_created` datetime DEFAULT NULL,
	    `time_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		`deleted` tinyint(1) NOT NULL DEFAULT '0',
		`restricted` tinyint(1) NOT NULL DEFAULT '0',
        
		    `title` VARCHAR(250) DEFAULT NULL  COMMENT 'Title',
		    `type` VARCHAR(500) DEFAULT NULL  COMMENT 'Type',
		    `subline` VARCHAR(250) DEFAULT NULL  COMMENT 'Subline',
		    `live` BOOLEAN  DEFAULT '0' COMMENT 'Live',
		    `module_prefix` INT(11) DEFAULT NULL  COMMENT 'Module Prefix',
		    `module_field` INT(11) DEFAULT NULL  COMMENT 'Module Field',
		    `compare_sign` VARCHAR(500) DEFAULT NULL  COMMENT 'Compare Sign',
		    `compared_value` VARCHAR(250) DEFAULT NULL  COMMENT 'Compared Value',
		    `size` VARCHAR(500) DEFAULT NULL  COMMENT 'Size',
		    `free_where` VARCHAR(250) DEFAULT NULL  COMMENT 'Free Where',
		    `order_number` INT(11) DEFAULT NULL  COMMENT 'Order Number',
		    `icon` VARCHAR(50) DEFAULT NULL  COMMENT 'Icon',
		    `dataset_1_label` VARCHAR(250) DEFAULT NULL  COMMENT 'Dataset 1 Label',
		    `dataset_1_color` VARCHAR(10) DEFAULT NULL  COMMENT 'Dataset 1 Color',
		    `dataset_1_opacity` INT(11)  DEFAULT '100' COMMENT 'Dataset 1 Opacity',
		    `dataset_1_free_where` VARCHAR(250) DEFAULT NULL  COMMENT 'Dataset 1 Free Where',
		    `dataset_1_state` VARCHAR(500)  DEFAULT 'Not Deleted' COMMENT 'Dataset 1 State',
		    `dataset_2_label` VARCHAR(250) DEFAULT NULL  COMMENT 'Dataset 2 Label',
		    `dataset_2_color` VARCHAR(10) DEFAULT NULL  COMMENT 'Dataset 2 Color',
		    `dataset_2_opacity` INT(11)  DEFAULT '100' COMMENT 'Dataset 2 Opacity',
		    `dataset_2_free_where` VARCHAR(250) DEFAULT NULL  COMMENT 'Dataset 2 Free Where',
		    `dataset_2_state` VARCHAR(500)  DEFAULT 'Not Deleted' COMMENT 'Dataset 2 State',
		    `dataset_3_label` VARCHAR(250) DEFAULT NULL  COMMENT 'Dataset 3 Label',
		    `dataset_3_color` VARCHAR(10) DEFAULT NULL  COMMENT 'Dataset 3 Color',
		    `dataset_3_opacity` INT(11)  DEFAULT '100' COMMENT 'Dataset 3 Opacity',
		    `dataset_3_free_where` VARCHAR(250) DEFAULT NULL  COMMENT 'Dataset 3 Free Where',
		    `dataset_3_state` VARCHAR(500)  DEFAULT 'Not Deleted' COMMENT 'Dataset 3 State',
		    `dataset_4_label` VARCHAR(250) DEFAULT NULL  COMMENT 'Dataset 4 Label',
		    `dataset_4_color` VARCHAR(10) DEFAULT NULL  COMMENT 'Dataset 4 Color',
		    `dataset_4_opacity` INT(11)  DEFAULT '100' COMMENT 'Dataset 4 Opacity',
		    `dataset_4_free_where` VARCHAR(250) DEFAULT NULL  COMMENT 'Dataset 4 Free Where',
		    `dataset_4_state` VARCHAR(500)  DEFAULT 'Not Deleted' COMMENT 'Dataset 4 State',
		    `dataset_5_label` VARCHAR(250) DEFAULT NULL  COMMENT 'Dataset 5 Label',
		    `dataset_5_color` VARCHAR(10) DEFAULT NULL  COMMENT 'Dataset 5 Color',
		    `dataset_5_opacity` INT(11)  DEFAULT '100' COMMENT 'Dataset 5 Opacity',
		    `dataset_5_free_where` VARCHAR(250) DEFAULT NULL  COMMENT 'Dataset 5 Free Where',
		    `dataset_5_state` VARCHAR(500)  DEFAULT 'Not Deleted' COMMENT 'Dataset 5 State',
		    `chart_type` VARCHAR(500) DEFAULT NULL  COMMENT 'Chart Type',
		    `axis` VARCHAR(500) DEFAULT NULL  COMMENT 'Axis',
		    `colors` VARCHAR(500) DEFAULT NULL  COMMENT 'Colors',
		    `hide_zeros` BOOLEAN  DEFAULT '1' COMMENT 'Hide Zeros',
		    `fill` BOOLEAN  DEFAULT '0' COMMENT 'Fill',
		    `vs_time` BOOLEAN  DEFAULT '0' COMMENT 'Vs Time',
		    `days` INT(11) DEFAULT NULL  COMMENT 'Days',
		    `stacked` BOOLEAN  DEFAULT '0' COMMENT 'Stacked',
		    `button_title` VARCHAR(250) DEFAULT NULL  COMMENT 'Button Title',
		    `button_link` VARCHAR(1000) DEFAULT NULL  COMMENT 'Button Link',
PRIMARY KEY (`id`),
INDEX (`deleted`)

) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;