<?php

function disk($path){
	$io = popen('/usr/bin/du -sb '.$path, 'r');
    $_root_size = intval(fgets($io,80));
    pclose($io);
	
	return [
		'bytes'=>$_root_size,
		'm'=>mb($_root_size),
		'g'=>mb($_root_size,'G')
		];
}

function manifestJson(){
$settings=db('settings',"WHERE id=1",NULL,"LIMIT 1")[0];
	
	//manifest file update
	$myfile = fopen(cms_dir."/manifest.json", "w") or die("Unable to open file! - manifest.json");
	$txt = "{
  \"name\": \"".l($settings['site_name'])."\",
  \"short_name\": \"".l($settings['site_short_name'])."\",
  \"lang\": \"".detail('languages_1557157519','prefix','id',$settings['language'])."\",
  \"start_url\": \"".url."\",
  \"display\": \"standalone\",
    \"description\": \"".trim(preg_replace('/\s+/', ' ', strip_tags(l($settings['site_desc']))))."\",
  \"theme_color\": \"".$settings['main_color']."\",
  \"background_color\": \"".$settings['sub_menu_color']."\",
  	\"icons\": [
  {
    \"src\": \"".u.img($settings['logo'],192,100,false,192)."\",
    \"sizes\": \"192x192\"
  },
		 {
    \"src\": \"".u.img($settings['logo'],512,100,false,512)."\",
    \"sizes\": \"512x512\",
	\"purpose\": \"any maskable\"
  }
]
}
	";
	fwrite($myfile, $txt);
	fclose($myfile);
	
	
	//offline page update, for service worker
	$myfile = fopen(cms_dir."/offline.html", "w") or die("Unable to open file! - offline.html");
	$txt = rights."

<!doctype html>
<html>
<head> 
<meta charset=\"UTF-8\">
<meta http-equiv=\"expires\" content=\"0\">
<title>".$settings['site_name']."</title>
	<link rel=\"shortcut icon\" type=\"image/png\" href=\"uploads/default_fav.png\"/>

</head>

<body>
<div id=\"no_block\">
<img src=\"uploads/nointernet.png\" alt=\"No internet connection\"/>
<div id=\"no_text\">
Check your internet connection. 
	</div>
	</div>


<footer>

		<div id=\"provision\">
			<a target=\"_blank\" href=\"https://provision.ps\" title=\"Go to ProVision's website\">
				<span>website by</span>
				<img alt=\"ProVision\" src=\"uploads/default_logo.png\"/>
			</a>
	</div>
</footer>

</body>
</html>
<style>
	a:visited, a:link {
    color: inherit;
    text-decoration: none;
}
	body {
    text-align: center;
    background: whitesmoke;
    padding: 10%;
		font-family: monospace;
}
	#no_text {
    font-size: 20px;
}
	footer{margin-top:30px;}
	
		#provision span {
  font-size: 8px;
}

	#provision img {
    width: 60px;
    vertical-align: middle;
	margin-bottom: unset;
}


</style>

	";
	fwrite($myfile, $txt);
	fclose($myfile);
}

function colors(){
	global $settings;
	$classes="/*palette*/";


	$txt=":root{
		--mc:".$settings['main_color'].";
		--mainColor:".$settings['main_color'].";
		--sub_menu_color:".$settings['sub_menu_color'].";


		/*Variables generated by Legion Engine*/
";
	
	
	 $colors=db('color_palette_1645099749');
		 if($colors!=1 && $colors!=0){
			 foreach($colors as $color){
				$tmp_name=strtolower((str_replace(' ','',l($color['name']))));

				$classes.='
				.p_'.$tmp_name.'{background-color:'.$color['color'].'}
				.p_'.$tmp_name.'_i{background-color:'.$color['color'].' !important}
				.p_'.$tmp_name.'_c'.'{color:'.$color['color'].'}
				.p_'.$tmp_name.'_c_i'.'{color:'.$color['color'].' !important;}
				';
				
				 $txt.="--".$tmp_name.":".$color['color'].";
				 ";
			 }
		 }
		 
	$txt.="
}
";


$myfile = fopen(pres_dir.'css/colors.css', "w") or json(false,29);
	
	fwrite($myfile, $txt.$classes);
	fclose($myfile);
}



function getBrowser() {
  $u_agent = $_SERVER['HTTP_USER_AGENT'];
  $bname = 'Unknown';
  $platform = 'Unknown';
  $version= "";
  // First get the platform?
  if (preg_match('/linux/i', $u_agent)) {
    $platform = 'linux';
  } elseif (preg_match('/macintosh|mac os x/i', $u_agent)) {
    $platform = 'mac';
  } elseif (preg_match('/windows|win32/i', $u_agent)) {
    $platform = 'windows';
  }
  // Next get the name of the useragent yes seperately and for good reason
  if(preg_match('/MSIE/i',$u_agent) && !preg_match('/Opera/i',$u_agent)) {
    $bname = 'Internet Explorer';
    $ub = "MSIE";
  } elseif(preg_match('/Firefox/i',$u_agent)) {
    $bname = 'Mozilla Firefox';
    $ub = "Firefox";
  } elseif(preg_match('/Chrome/i',$u_agent)) {
    $bname = 'Google Chrome';
    $ub = "Chrome";
  } elseif(preg_match('/Safari/i',$u_agent)) {
    $bname = 'Apple Safari';
    $ub = "Safari";
  } elseif(preg_match('/Opera/i',$u_agent)) {
    $bname = 'Opera';
    $ub = "Opera";
  } elseif(preg_match('/Netscape/i',$u_agent)) {
    $bname = 'Netscape';
    $ub = "Netscape";
  }
  // finally get the correct version number
  $known = array('Version', $ub, 'other');
  $pattern = '#(?<browser>' . join('|', $known) . ')[/ ]+(?<version>[0-9.|a-zA-Z.]*)#';
  if (!preg_match_all($pattern, $u_agent, $matches)) {
    // we have no matching number just continue
  }
  // see how many we have
  $i = count($matches['browser']);
  if ($i != 1) {
    //we will have two since we are not using 'other' argument yet
    //see if version is before or after the name
    if (strripos($u_agent,"Version") < strripos($u_agent,$ub)){
      $version= $matches['version'][0];
    } else {
      $version= $matches['version'][1];
    }
  } else {
    $version= $matches['version'][0];
  }
  // check if we have a number
  if ($version==null || $version=="") {$version="?";}
return array(
  'userAgent' => $u_agent,
  'name'      => $bname,
  'version'   => $version,
  'platform'  => $platform,
  'pattern'    => $pattern
  );
}

function underConstruction(){
	global $legion;
	$settings=db('settings',"WHERE id=1",NULL,"LIMIT 1")[0];

	//offline page update, for service worker
	$myfile = fopen(cms_dir."/index.html", "w") or die("Unable to open file! - index.html");
	$txt = rights."
<!doctype html>
<html>
<head> 
<meta charset=\"UTF-8\">
<title>".$settings['site_name']." | Under Construction</title>
	<link rel=\"shortcut icon\" type=\"image/png\" href=\"".u.$settings['fav']."\"/>
<meta content=\"".$settings['author']."\" name=\"author\"/>
<meta content=\"LEGION Engine - ProVision\" name=\"engine\"/>
<meta content=\"".$legion['website_link']."\" name=\"engine link\"/>
<meta name=\"ROBOTS\" content=\"NOINDEX,NOFOLLOW\">
</head>

<body>
<div id=\"no_block\">
<img src=\"".u.img($settings['logo'],300,100)."\" alt=\"".$settings['site_name']." Logo\" />
<div id=\"no_text\">
under construction
	</div>
	</div>


<footer>

		<div id=\"provision\">
			<a target=\"_blank\" href=\"https://provision.ps\" title=\"Go to ProVision's website\">
				<span>website by</span>
				<img alt=\"ProVision\" src=\"uploads/default_logo.png\"/>
			</a>
	</div>
</footer>
".connection('g_analytics')."
</body>
</html>
<style>
	a:visited, a:link {
    color: inherit;
    text-decoration: none;
}
	body {
    text-align: center;
    background: whitesmoke;
    padding: 10%;
		font-family: monospace;
}
	#no_text {
    font-size: 20px;
}
	footer{margin-top:30px;}
		#provision span {
  font-size: 8px;
}

	#provision img {
    width: 60px;
    vertical-align: middle;
	margin-bottom: unset;
}
img{    max-width: 40vw;
    margin-bottom: 30px;
    max-height: 40vh;}
</style>

	";
	fwrite($myfile, $txt);
	fclose($myfile);


} 

function deleteUnderConstruction(){
	if(file_exists(public_html.'index.html'))
	trash(public_html.'index.html');
}

function getAddresses($domain) {
  $records = dns_get_record($domain);
  $res = array();
  foreach ($records as $r) {
    if ($r['host'] != $domain) continue; // glue entry
    if (!isset($r['type'])) continue; // DNSSec

    if ($r['type'] == 'A') $res[] = $r['ip'];
    if ($r['type'] == 'AAAA') $res[] = $r['ipv6'];
  }
  return $res;
}

function getAddresses_www($domain) {
  $res = getAddresses($domain);
  if (count($res) == 0) {
    $res = getAddresses('www.' . $domain);
  }
  return $res;
}

function block(){
	if(isset($_SESSION['attempt']))$_SESSION['attempt']++;
	else $_SESSION['attempt']=0;
	
	if($_SESSION['attempt']>=3335){
		if(!isset($_SESSION['block_end_time'])){
			$_SESSION['block_end_time']=time()+900;
			json(false,14);//if not set
					}
		else {
			if(time()>=$_SESSION['block_end_time']){
				unset($_SESSION['block_end_time']);
				$_SESSION['attempt']=0;
				}
			else
				json(false,14);
			
			}
		
		}
	
	}

function modules_action_inserter($id,$menu_serial){
	global $conn;
	
	//legacy
//	if(db('module_actions')==0)
//		$target_module='modules_actions';
//	else
		$target_module='module_actions';
	//legacy
	
	
	//delete the old
	mysqli_query($conn,"UPDATE $target_module SET deleted=1 WHERE module_id='$id'");
	
	
	$subs=unserialize($menu_serial);
	for($j=0;$j<count($subs);$j++){
		$tmp=db($target_module,"WHERE deleted=1 AND module_id=$id AND icon='".$subs[$j]['icon']."' AND title='".$subs[$j]['title']."' AND type='".$subs[$j]['type']."'",NULL,"LIMIT 1");


	if($tmp==1)
		mysqli_query($conn,"INSERT INTO $target_module (admin_add_id,module_id,title,icon,type) VALUES ('".$_SESSION['user_id']."','$id','".$subs[$j]['title']."','".$subs[$j]['icon']."','".$subs[$j]['type']."')");
	else
		$tmp=mysqli_query($conn,"UPDATE $target_module SET deleted=0 WHERE id='".$tmp[0]['id']."' LIMIT 1");
	}
	
	
	$tmp=db($target_module,"WHERE deleted=1 AND module_id=$id AND icon='edit' AND title='Edit<>تعديل' AND type='edit'",NULL,"LIMIT 1");
	
	if($tmp==1)
		mysqli_query($conn,"INSERT INTO $target_module (admin_add_id,module_id,title,icon,type) VALUES ('".$_SESSION['user_id']."','$id','Edit<>تعديل','edit','edit')");
	
	else
		mysqli_query($conn,"UPDATE $target_module SET deleted=0 WHERE id='".$tmp[0]['id']."' LIMIT 1");
	
	

	//remove the old and insert sub actions that came with the info.php of the module
	mysqli_query($conn,"DELETE FROM $target_module WHERE module_id='$id' AND deleted=1");
}

function trash($dir) {
	if(is_dir($dir) && $dir!=NULL && $dir!='' && $dir!=' ' && $dir!='../' && $dir!='./' && $dir!='/')delTree($dir);
	else return file_exists($dir)?unlink($dir):NULL;
}

function delTree($dir) { 
   $files = array_diff(scandir($dir), array('.','..')); 
    foreach ($files as $file) { 
      (is_dir("$dir/$file")) ? delTree("$dir/$file") : unlink("$dir/$file"); 
    } 
    return rmdir($dir); 
  } 

function active($item_id,$active,$module_prefix,$booleanField){
	if($active){
		return "<a id=\"switch_".$booleanField."_$item_id\" class=\"onSwitch nos  po\" onclick=\"return submitter(null,urlPanel,'switching',{ 'module' : 'active','module_prefix':'$module_prefix','id' : $item_id,'e':'','booleanField':'$booleanField'},'post',false);\">On</a>";
	}
	else return "<a id=\"switch_".$booleanField."_$item_id\" class=\"offSwitch nos po\"  onclick=\"return submitter(null,urlPanel,'switching',{ 'module' : 'active','module_prefix':'$module_prefix','id' : $item_id,'e':'','booleanField':'$booleanField'},'post',false);\">Off</a>";
}

function indexer($dirWithSlash,$fileName='index',$type='php',$data=NULL){
	if(!file_exists($dirWithSlash))mkdir($dirWithSlash,0755);
	$myfile = fopen($dirWithSlash.$fileName.'.'.$type, "w") or json(false,3);
	switch ($type){
case'css':case'js':
			$txt='/*'.rights_txt.'*/';
			break;
			case'txt':
			$txt='';
			break;
				default:
	$txt = "<?php
//ProVision is the best";
			break;
			
			}
	fwrite($myfile, $txt.$data);
//	die($data);
	fclose($myfile);
	
}






function engNum($string) {
    $newNumbers = range(0, 9);
    // 1. Persian HTML decimal
    $persianDecimal = array('&#1776;', '&#1777;', '&#1778;', '&#1779;', '&#1780;', '&#1781;', '&#1782;', '&#1783;', '&#1784;', '&#1785;');
    // 2. Arabic HTML decimal
    $arabicDecimal = array('&#1632;', '&#1633;', '&#1634;', '&#1635;', '&#1636;', '&#1637;', '&#1638;', '&#1639;', '&#1640;', '&#1641;');
    // 3. Arabic Numeric
    $arabic = array('٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩');
    // 4. Persian Numeric
    $persian = array('۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹');

    $string =  str_replace($persianDecimal, $newNumbers, $string);
    $string =  str_replace($arabicDecimal, $newNumbers, $string);
    $string =  str_replace($arabic, $newNumbers, $string);
    return str_replace($persian, $newNumbers, $string);
}

function fixPhone($phone){
	$phone=escape($phone);
	$phone=str_replace(' ','',$phone);
	$phone=engNum($phone);
	$phone=substr($phone,-9);
	return $phone;
}

function psCountryCodeFromMobile($phone){
	$countrycode=substr($phone,0,2);
	if($countrycode=='56' || $countrycode=='59')$countrycode='00970';else $countrycode='00972';
	return $countrycode;
}

//$countrycode must be number, for example: 970, but if you put (ps) it will save you time determining which country phone code needs to be used.
//$sender can be null as legioncms.com will use the main sender name assigned to this website
function sms($to,$msg,$token=NULL,$countrycode='ps',$sender=NULL,$log=false){
	if(function_exists('smss'))return smss($to,$msg,$countrycode,$sender,$log);

	global $conn,$admin_add_id,$date_created;

	if($token==NULL && defined('legion_token'))//it means that you made: define('legion_token','xxxxx') in custom_config
		$token=constant('legion_token');

	$to=fixPhone($to);
	if($countrycode=='ps')$countrycode=psCountryCodeFromMobile($to);

	$fields = array(
        'api'=>'sms',
        'action'=>'send',
        'token'=>password_hash($token,PASSWORD_DEFAULT),
        'sender'=>$sender,
        'phone'=>$to,
        'country_code'=>$countrycode,
        'msg'=>$msg,
        'web_link'=>main_url
    );


        $ch = curl_init();
        curl_setopt($ch,CURLOPT_URL,'https://legioncms.com/api/1.0/');
        curl_setopt($ch,CURLOPT_POST,true);
        curl_setopt($ch,CURLOPT_POSTFIELDS,$fields);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

        //execute post
        $result = curl_exec($ch);
		if($log)m($result);
        // d($result);
        //print $result;
        $_POST['action']=$action='add';
        $_POST['internal']=true;
        list($_POST['country_code'],$_POST['phone_number'],$_POST['message'])=array($countrycode,$to,$msg);
        require modules_dir.'sms_1583164170/models/add.php';
}


function sms_balance($log=false){
	if(function_exists('smss_balance'))return smss_balance();


	if(defined('legion_token'))//it means that you made: define('legion_token','xxxxx') in custom_config
		$token=constant('legion_token');
	else
		return 'NA';

	$fields = array(
        'api'=>'sms',
        'action'=>'balance',
        'token'=>password_hash($token,PASSWORD_DEFAULT),
        'web_link'=>main_url
    );


        $ch = curl_init();
        curl_setopt($ch,CURLOPT_URL,'https://legioncms.com/api/1.0/');
        curl_setopt($ch,CURLOPT_POST,true);
        curl_setopt($ch,CURLOPT_POSTFIELDS,$fields);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

        //execute post
        $result = curl_exec($ch);
		if($log)m($result);

		if($result!=NULL){
			$res=json_decode($result,true);
			return $res['data'];
		}
		return 'ERROR';
}


function undo1(){
	global $new_folder_name;
	trash(modules_dir.$new_folder_name);
}

function undo2(){
	global $new_folder_name,$conn;
	#if the new table succeeded to be created, remove it to prepare to get back to the old one
	if(db($new_folder_name,NULL,NULL,'LIMIT 1')!=0){
		if(!mysqli_query($conn,"DROP TABLE $new_folder_name"))json(false,62);
	}
}

function undo4(){
	global $conn,$new_folder_name;
	if(!mysqli_query($conn,"DELETE FROM module_settings WHERE module_prefix='$new_folder_name'"))json(false,62);
}


function undo5(){
	global $conn,$new_folder_name;
	if(!mysqli_query($conn,"DELETE FROM modules WHERE module_prefix='$new_folder_name'"))json(false,62);
}


function undo_1(){
	global $conn,$temp_table,$module_folder;
	if(!mysqli_query($conn,"RENAME TABLE $temp_table TO $module_folder"))json(false,60);
}

function undo_2(){
	global $conn,$temp_folder,$module_folder;
	if(!rename(modules_dir.$temp_folder,modules_dir.$module_folder))json(false,60);
}

function undo_4(){
	global $module_folder;
	trash(modules_dir.$module_folder);
}

function undo_5(){
	global $conn,$temp_folder,$module_folder;
	
	#delete the new settings
	mysqli_query($conn,"DELETE FROM module_settings WHERE module_prefix='$module_folder' AND deleted='0'");
	#restore the old settings
	mysqli_query($conn,"UPDATE module_settings SET deleted='0' WHERE module_prefix='$module_folder' LIMIT 1");

	#if the new table succeeded to be created, remove it to prepare to get back to the old one
	if(db($module_folder,NULL,NULL,'LIMIT 1')!=0){
		if(!mysqli_query($conn,"DROP TABLE $module_folder"))json(false,60);
	}
}




function undo_6(){
	global $conn,$module_id;
	if(!mysqli_query($conn,"UPDATE module_fields SET deleted=0 WHERE module_id='$module_id'"))json(false,62);
}



function slugify($text,$divider='-')
{
	if($text==NULL)return $text;
  // replace non letter or digits by divider
  $text = preg_replace('~[^\pL\d]+~u', $divider, $text);

  // transliterate
//   $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);

  // remove unwanted characters
  $text = preg_replace('~[^-\w]+~u', '', $text);

  // trim
  $text = trim($text, $divider);

  // remove duplicate divider
  $text = preg_replace('~-+~', $divider, $text);


	//arabic and hebrew
	// $text = preg_replace('/[\p{Arabic}\p{Hebrew}]/u', "", $text);
	

	
	
  // lowercase
  $text = strtolower($text);

  if(empty($text)) {
    return NULL;
  }

  return $text;
}


function getContents($str, $startDelimiter, $endDelimiter) {
  if($str==NULL)return $str;
  $contents = array();
  $startDelimiterLength = strlen($startDelimiter);
  $endDelimiterLength = strlen($endDelimiter);
  $startFrom = $contentStart = $contentEnd = 0;
//   mark($str);
  while (false !== ($contentStart = strpos($str, $startDelimiter, $startFrom))) {
    $contentStart += $startDelimiterLength;
    $contentEnd = strpos($str, $endDelimiter, $contentStart);
    if (false === $contentEnd) {
      break;
    }
    $contents[] = substr($str, $contentStart, $contentEnd - $contentStart);
    $startFrom = $contentEnd + $endDelimiterLength;
  }

  return $contents;
}


function meepo($txt){
	
	$match=getContents($txt,'#','#');
	for($i=0;$i<count($match);$i++){ 
		$tmp=db('meepo_1646265283',"WHERE id='".$match[$i]."'");
		if($tmp!=1)
			$txt=str_replace('#'.$match[$i].'#',$tmp[0]['html'],$txt);
	}
	return $txt;
}


function entry_history($entry_module_prefix,$entry_id,$action=NULL){
	$echo='';
	if($entry_id==NULL)return $echo;

	$resp=db('entries_log_8503',"WHERE !deleted AND entry_module=".mid($entry_module_prefix)." AND entry_id=$entry_id",NULL,'LIMIT 10');
	
	if($resp!=1){
		$echo.='<div class="l_mt10 l_f12 l_mb5">'.l('Entry History<>تاريخ المُدخل').'</div>';
		$echo.='<div class="l_gray_c l_f11">';
		foreach($resp as $r){
			$echo.='<div class="l_mb2">';
			if(dim($r['user_module'])=='admins'){
				$admin=o('admins',$r['user_id'])[0];
				if($admin['first_name']!='')$echo.=$admin['first_name'].' ';
				if($admin['last_name']!='')$echo.=$admin['last_name'].' ';
				if($admin['first_name']=='' && $admin['last_name']=='')$echo.=$admin['username'].' ';
			}
			$echo.=l('did<>عمل').' ';

			switch($r['action']){
				case'edit':$echo.=l('edit<>تعديل').' ';break;
				case'add':$echo.=l('add<>أضاف').' ';break;
				case'delete':$echo.=l('delete<>حذف').' ';break;
				case'copy':$echo.=l('copy<>نسخ').' ';break;
				case'restore':$echo.=l('restore<>استرجع').' ';break;
				case'active':$echo.=l('toggle<>غير').' '.$r['remark'];break;
				
				default: $echo.=$r['action'].' ';
			}

			$echo.=l('on<>في').': '.$r['date_created'];
			if($r['remark']!='')
				$echo.=' ['.l('remark<>ملاحظة').': '.l($r['remark']).']';
			$echo.='</div>';
		}
		$echo.='</div>';
	}

	
	return $echo;
}

function autoMetaResetter(){
	
  
	$resp=db('link_handler_1566934564');
	$txt=NULL;
	$first=true;
	$phrase="if";
	
	if($resp!=1){
	foreach($resp as $elem){
		$modulePrefix=detail('modules','module_prefix','id',$elem['module_prefix']);
		
		if($elem['all_entries']!=''){
			
		$txt.="
		$phrase(strpos(\$uri,'/".$elem['all_entries']."')!==false){
			\$link_handler=o('link_handler_1566934564','".$elem['all_entries']."','all_entries')[0];
			if(l(\$link_handler['all_entries_title'])==NULL)
				\$seo_title=mn('".$modulePrefix."');
			else
				\$seo_title=l(\$link_handler['all_entries_title']);

			if(l(\$link_handler['all_entries_description'])==NULL)
				\$seo_desc=\$metaArray['desc'];
			else
				\$seo_desc=l(\$link_handler['all_entries_description']);
			
			\$post['title']=\$seo_title;
			\$post['desc']=\$seo_desc;

			\$seo_desc=strip_tags(\$seo_desc);

			
			\$metaArray['title']=\$seo_title;
			\$metaArray['desc']=\$seo_desc;".
		($elem['all_entries_photo']==''?NULL:"\$metaArray['image']=u.'".$elem['all_entries_photo']."';").
		"
		}";
		
			$first=false;
			$phrase="else if";
}
		
		
if($elem['single']!=''){
			
	$slug=db('module_fields',"WHERE module_id='".$elem['module_prefix']."' AND field_name='slug'",NULL,'LIMIT 1');
	

	
	if($slug!=1){
		$indicator_field='slug';
		$add_indicator=" OR (slug='\$indicator' OR slug LIKE '\$indicator<>%' OR slug LIKE '%<>\$indicator' OR slug LIKE '%<>\$indicator<>%')";
	}
	else {
		$indicator_field='id';
		$add_indicator=NULL;
	}
	
	
$txt.="
$phrase(strpos(\$uri,'/".$elem['single']."')!==false){
	\$post=db('".$modulePrefix."',\"WHERE !deleted AND ($indicator_field='\$indicator' $add_indicator)\",NULL,\"LIMIT 1\");

	

	if(\$post==1){header('location:'.url.'error/404/'.curr());exit;}
	\$post=\$post[0];

	\$seo_custom=db('seo_custom_852526',\"WHERE !deleted AND module_id='".mid($modulePrefix)."' AND related_id='\".\$post['id'].\"'\");
	
	\$single_seo_title_field='".detail('module_fields','field_name','id',$elem['single_title'])."';
	\$single_seo_title_field_alt='".detail('module_fields','field_name','id',$elem['single_title_alternative'])."';

	\$single_seo_desc_field='".detail('module_fields','field_name','id',$elem['single_description'])."';
	\$single_seo_desc_field_alt='".detail('module_fields','field_name','id',$elem['single_alternative'])."';
	
	\$single_seo_photo_field='".detail('module_fields','field_name','id',$elem['single_photo'])."';

	if(\$seo_custom!=1 && l(\$seo_custom[0]['title'])!='')\$_final_seo_title=l(\$seo_custom[0]['title']);
	elseif(isset(\$post[\$single_seo_title_field]))\$_final_seo_title=l(\$post[\$single_seo_title_field]);
	else \$_final_seo_title=l(\$post[\$single_seo_title_field_alt]);

	if(\$seo_custom!=1 && l(\$seo_custom[0]['description'])!='')\$_final_seo_desc=l(\$seo_custom[0]['description']);
	elseif(isset(\$post[\$single_seo_desc_field]))\$_final_seo_desc=sl(\$post[\$single_seo_desc_field]);
	else \$_final_seo_desc=sl(\$post[\$single_seo_desc_field_alt]);


	if(\$_final_seo_title!='')
		\$metaArray['title']=\$metaArray['title'].\$metaArray['sep'].\$_final_seo_title;

	if(\$_final_seo_desc!='')
		\$metaArray['desc']=\$_final_seo_desc;

	";
	
	if($elem['single_photo']!=0)
		$txt.="

	if(\$seo_custom!=1 && \$seo_custom[0]['photo']!='' && file_exists(target_dir.\$seo_custom[0]['photo'])){
		\$metaArray['image']=u.\$seo_custom[0]['photo'];
		\$seo_image_size=getimagesize(target_dir.\$seo_custom[0]['photo']);
		\$metaArray['image_width']=\$seo_image_size[0];
		\$metaArray['image_height']=\$seo_image_size[1];
	}
	elseif(\$post[\$single_seo_photo_field]!='' && file_exists(target_dir.\$post[\$single_seo_photo_field])){
		\$metaArray['image']=u.\$post[\$single_seo_photo_field];
		\$seo_image_size=getimagesize(target_dir.\$post[\$single_seo_photo_field]);
		\$metaArray['image_width']=\$seo_image_size[0];
		\$metaArray['image_height']=\$seo_image_size[1];
	}";

	$txt.='}';

	$first=false;
	$phrase="else if";

}










	}
}
	indexer(cms_dir,'autoMeta','php',$txt);
	
}



function fieldsProcess($resp,$fields,$module,$td=false,$as_db=false){

	if($resp==1 || $resp==NULL)return $resp;
	
	$res=array();
	foreach($fields as $f){
		
		$fn=$f['field_name'];
		if($as_db){
			$res[$fn]=$resp[$fn];
			continue;
		}
		
		$style='border:1px solid gray;';		
		switch($f['type']){
				case'date':
					// d($resp[$fn]);
					if($resp[$fn]==NULL)$res[$fn]=NULL;
					else $res[$fn]=$resp[$fn];
				break;

				case'file':
				if($resp[$fn]==NULL)$res[$fn]=NULL;
				if($f['sub_type']=='photo' || $f['sub_type']=='file'){
					if($f['multi_files']){
						$tmp=NULL;
						$files=array();
						$x=explode(',',$resp[$fn]);
						if($x==false){
							$res[$fn]=NULL;
							break;
						}
						foreach($x as $file){
							$files[]=o('files_1577206823',$file,'name')[0]['full_name'];
						}
						
						
						foreach($files as $z){
							if($td)
								$tmp.='<a href="'.($f['protected_file']==0?u:d).$z.'">'.($f['protected_file']==0?u:d).$z.'</a>'.',';
							else
								$tmp.=($f['protected_file']==0?u:d).$z.',';
						}
						$res[$fn]=rtrim($tmp,',');
					}else{
						$link=($f['protected_file']==0?u:d).$resp[$fn];
						if($td)$link='<a href="'.$link.'">'.$resp[$fn].'</a>';
						 $res[$fn]=$resp[$fn]==NULL?NULL:$link;
					}
				}
				break;


				case 'select':
				$x=explode(',',$f['select_field']);

				$final=NULL;
				if($f['sub_type']=='multi'){
					$tmp=comp($module,$resp['id'],$f['select_table']);
					if($tmp==1)$res[$fn]='';
					else{
						foreach($tmp as $t){
							 for($i=0;$i<count($x);$i++){
								if($x[$i]=='-')$sep=' '.$x[$i];else $sep=' ';
								$final.=$sep.l(detail($f['select_table'],$x[$i],'id',$t['child_id']));
							}
						}
						$res[$fn]=$final;
					}

					break;
				}


				for($i=0;$i<count($x);$i++){
					if($x[$i]=='-')$sep=' '.$x[$i];else $sep=' ';
					$final.=$sep.l(detail($f['select_table'],$x[$i],'id',$resp[$fn]));
				}

				$res[$fn]=$final;
				break;

				case'checkbox':
					$res[$fn]=boolval($resp[$fn]);
				break;

				case'password':
					$res[$fn]='***';
				break;
				
				case'color':
					$style='border:1px solid gray;background:'.$resp[$fn].';';
				break;

			default:
				$res[$fn]=l($resp[$fn]);
		}
		
		if($td){
			$res[$fn]='<td style="mso-number-format:\'\@\';'.($style==NULL?NULL:$style.'"').'">'.$res[$fn].'</td>';
		}
		
	}
	
	return $res;
}



function moduleFields($module){	
	if(file_exists(modules_dir.$module['module_prefix'].'/others/fieldsArray.php')){
	$fields=json_decode(file_get_contents(modules_dir.$module['module_prefix'].'/others/fieldsArray.php'),true);
// pre($fields);
	$tmp=array();
	for($i=0;$i<count($fields);$i++){
		$resp=db('module_fields',"WHERE module_id='".$module['module_id']."' AND deleted=0 AND field_name='".$fields[$i]['field_name']."'");
		if($resp!=1)$tmp[]=$resp[0];
	}
	
	$module['fields']=$tmp;
	}else
		$module['fields']=db('module_fields',"WHERE module_id='".$module['module_id']."'","ORDER BY id ASC",NULL);
	
	$f=array();
	
	$main_field_arr[0]='select';
	$main_field_arr[1]='id';
	$main_field_arr[2]='options';
	
	
	
	for($u=0;$u<count($module['fields']);$u++){
		$f[$module['fields'][$u]['field_name']]=$module['fields'][$u];
		if($module['fields'][$u]['main'])
			$main_field_arr[]=$module['fields'][$u]['field_name'];
	}
		
	
	$f['options']=array('label'=>'Options<>خيارات','type'=>'legion');
	$f['select']=array('label'=>'','type'=>'legion');
	$f['id']=array('label'=>'ID<>رقم','type'=>'number','field_name'=>'id');

	return array($module,$main_field_arr,$f,$module['fields']);
}
